version: '3'

services:
  mongodb:
    build: ./docker/mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    #    volumes:
    #      - mongodb-data:/var/lib/mongodb/data
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'rs.status().ok'
      interval: 10s
      timeout: 5s
      retries: 5
